pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'mvn clean package'
      }
    }
    stage('Deploy') {
      steps {
        sh 'scp -i /path/to/your-key.pem target/java-app.war ec2-user@<ec2-public-ip>:/opt/tomcat/webapps/'
      }
    }
  }
}
